"""add break time

Revision ID: 527b9b3e738d
Revises: bd913a98560c
Create Date: 2020-12-10 22:09:53.542789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527b9b3e738d'
down_revision = 'bd913a98560c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('break_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'break_time')
    # ### end Alembic commands ###
