"""add sessions column

Revision ID: 7cabd95182eb
Revises: 77baf2330c5e
Create Date: 2020-12-09 17:39:24.717698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cabd95182eb'
down_revision = '77baf2330c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sessions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sessions')
    # ### end Alembic commands ###
