"""update user table

Revision ID: bd913a98560c
Revises: 7cabd95182eb
Create Date: 2020-12-10 11:43:38.062254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd913a98560c'
down_revision = '7cabd95182eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('type_of_break', sa.String(length=140), nullable=True))
    op.create_index(op.f('ix_user_type_of_break'), 'user', ['type_of_break'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_type_of_break'), table_name='user')
    op.drop_column('user', 'type_of_break')
    op.drop_column('user', 'time')
    # ### end Alembic commands ###
